services:
  api:
    profiles: ["api"]
    container_name: litestar.api
    build:
      context: .
      dockerfile: Dockerfile
      target: development
      # target: production
    expose:
      - "8000"
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
      - ./config:/app/config:ro
    environment:
      - CONFIG_PATH=${CONFIG_PATH:-./config/prod_config.toml}
    command: uvicorn src.presentation.api.main:init_api --host 0.0.0.0 --port 8000 --reload
    healthcheck:
      test: ["CMD-SHELL", "curl -fsSL http://localhost:8000/healthcheck/"]
      interval: 10s
      timeout: 60s
      retries: 5
      start_period: 10s
