services:
  api:
    profiles: ["api"]
    container_name: litestar.api
    build:
      context: .
      dockerfile: Dockerfile
      target: development
      # target: production
    expose:
      - "8000"
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
      - ./config:/app/config:ro
    networks:
      - litestar.postgres.network
      - litestar.mongo.network
      - litestar.kafka.network
    environment:
      - CONFIG_PATH=${CONFIG_PATH:-./config/config.toml}
    depends_on:
      kafka:
        condition: service_healthy
    # healthcheck:
    #   test: ["CMD-SHELL", "curl -fsSL http://localhost:8000/healthcheck/"]
    #   interval: 10s
    #   timeout: 60s
    #   retries: 5
    #   start_period: 10s

  postgres_migration:
    profiles: ["migration"]
    container_name: litestar.postgres_migration
    build:
      context: .
    restart: on-failure
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - litestar.postgres.network
    volumes:
      - ./config:/app/config:ro
      - ./alembic.ini:/app/alembic.ini:ro
      - ./src/infrastructure/db/migrations:/app/src/infrastructure/db/migrations:ro
    environment:
      - CONFIG_PATH=${CONFIG_PATH:-./config/prod_config.toml}
    command: ["python", "-m", "alembic", "upgrade", "head"]

  postgres:
    profiles: ["api", "migration"]
    container_name: litestar.postgres
    image: "postgres:16-alpine"
    hostname: user_service.postgres
    restart: unless-stopped
    expose:
      - "5432"
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - litestar.postgres.network
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: ${POSTGRES_USER:-$USER}
      POSTGRES_DB: ${POSTGRES_DB:-$USER}
    volumes:
      - litestar.postgres.data:/var/lib/postgresql/data:rw
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 60s
      retries: 5
      start_period: 10s

  postgres_backup:
    profiles: ["api"]
    container_name: litestar.postgres_backup
    image: prodrigestivill/postgres-backup-local:15-alpine
    networks:
      - litestar.postgres.network
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=${POSTGRES_DB:-$USER}
      - POSTGRES_USER=${POSTGRES_USER:-$USER}
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - BACKUP_DIR=/backups
      - POSTGRES_EXTRA_OPTS=-Z6 --schema=public --blobs
      - SCHEDULE=${POSTGRES_BACKUP_SCHEDULE:-@daily}
      - HEALTHCHECK_PORT=8080
    volumes:
      - ${POSTGRES_BACKUP_DIR:-./.backups/postgres}:/backups

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    expose:
      - "5050"

  mongodb:
    profiles: ["api"]
    container_name: litestar.mongodb
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - litestar.mongodb.data:/data/db
    networks:
      - litestar.mongo.network

  mongo-express:
    profiles: ["api"]
    container_name: litestar.mongo-express
    image: mongo-express
    restart: unless-stopped
    ports:
      - "28081:8081"
    networks:
      - litestar.mongo.network
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_DB_ADMIN_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_DB_ADMIN_PASSWORD}
      ME_CONFIG_MONGODB_URL: ${MONGO_DB_CONNECTION_URI}
    depends_on:
      - mongodb

  zookeeper:
    profiles: ["api", "kafka"]
    image: confluentinc/cp-zookeeper:latest
    container_name: main-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
    networks:
      - litestar.kafka.network

  kafka:
    profiles: ["api", "kafka"]
    image: confluentinc/cp-kafka:latest
    container_name: main-kafka
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    hostname: kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - litestar.kafka.network
    healthcheck:
      test: nc -z localhost 29092
      # interval: 10s
      # timeout: 10s
      # retries: 10
    # healthcheck:
    #   test: ["CMD", "kafka-broker-api-versions", "--bootstrap-server", "kafka:29092"]
    #   interval: 10s
    #   timeout: 10s
    #   retries: 10

  kafka-ui:
    profiles: ["api", "kafka"]
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - 8090:8080
    restart: unless-stopped
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:29092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
    links:
      - kafka
      - zookeeper
    networks:
      - litestar.kafka.network

  # create-topics:
  #   image: confluentinc/cp-kafka:latest
  #   container_name: create-topics
  #   depends_on:
  #     kafka:
  #       condition: service_healthy
  #   entrypoint:
  #     - /bin/sh
  #     - -c
  #     - |
  #       echo "Waiting for Kafka to be ready..."
  #       cub kafka-ready -b kafka:29092 1 20 && \
  #       kafka-topics --create --topic Chat --partitions 3 --replication-factor 1 --if-not-exists --bootstrap-server kafka:29092 && \
  #       kafka-topics --create --topic Message --partitions 2 --replication-factor 1 --if-not-exists --bootstrap-server kafka:29092 && \
  #       echo "Topics created!"
  #   networks:
  #     - litestar.kafka.network
  #   restart: "no"

  # create-topics:
  #   image: confluentinc/cp-kafka:latest
  #   container_name: create-topics
  #   depends_on:
  #     kafka:
  #       condition: service_healthy
  #   volumes:
  #     - ./entrypoint.sh:/usr/local/bin/entrypoint.sh
  #   entrypoint:
  #     - /bin/sh
  #     - /usr/local/bin/entrypoint.sh
  #   networks:
  #     - litestar.kafka.network
  #   restart: "no"

volumes:
  litestar.postgres.data:
  litestar.mongodb.data:

networks:
  litestar.postgres.network:
    driver: bridge
  litestar.mongo.network:
  litestar.kafka.network:
