"""

Revision ID: b09e736aafd2
Revises:
Create Date: 2024-09-06 17:48:39.907761

"""

from collections.abc import Sequence


# revision identifiers, used by Alembic.
revision: str = "b09e736aafd2"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
